[package]
name = "rust_math_lib"
author = "Christopher V. Maverick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
rand = "0.8.5"
